name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and Push Docker Image for rengine
      run: |
        docker buildx create --use
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker buildx build --platform linux/amd64,linux/arm64 -t vouu/rengine:(date +%s) ./web --push
